# Generated by Django 3.2 on 2025-04-05 15:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pages.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='certificates/', validators=[pages.validators.validate_image_file_size, pages.validators.validate_file_extension], verbose_name='Изображение сертификата')),
                ('title', models.CharField(max_length=100, verbose_name='Название сертификата')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание сертификата')),
                ('validity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Срок действия сертификата')),
                ('terms', models.TextField(blank=True, null=True, verbose_name='Условия использования сертификата')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone_numbers', models.JSONField(default=list, verbose_name='Телефонные номера')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('map_link', models.URLField(verbose_name='Ссылка на карту')),
                ('social_links', models.JSONField(default=dict, verbose_name='Социальные сети')),
            ],
            options={
                'verbose_name': 'Контактная страница',
                'verbose_name_plural': 'Контактные страницы',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя инструктора')),
                ('bio', models.TextField(verbose_name='Биография инструктора')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар инструктора')),
                ('room_photo', models.ImageField(blank=True, null=True, upload_to='instructors/', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Инструктор',
                'verbose_name_plural': 'Инструкторы',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Политика конфиденциальности',
                'verbose_name_plural': 'Политика конфиденциальности',
            },
        ),
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Правила пользования',
                'verbose_name_plural': 'Правила пользования',
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_video', models.FileField(blank=True, null=True, upload_to='videos/', validators=[pages.validators.validate_video_file_size, pages.validators.validate_file_extension], verbose_name='Видео приветствия')),
                ('background_photo', models.ImageField(blank=True, null=True, upload_to='images/', validators=[pages.validators.validate_image_file_size, pages.validators.validate_file_extension], verbose_name='Большое изображение')),
                ('big_text', models.TextField(blank=True, null=True, verbose_name='Большой текст (на первой фотографии)')),
                ('small_photo', models.ImageField(blank=True, null=True, upload_to='images/', validators=[pages.validators.validate_image_file_size, pages.validators.validate_file_extension], verbose_name='Малое изображение')),
                ('small_text', models.TextField(blank=True, null=True, verbose_name='Малый текст')),
                ('overlay_video_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст на видео')),
                ('event_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание мероприятий')),
                ('discount_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название скидки')),
                ('discount_description', models.TextField(blank=True, null=True, verbose_name='Описание скидки')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена без скидки')),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент скидки')),
                ('discount_validity', models.DateField(blank=True, null=True, verbose_name='Срок действия скидки')),
                ('certificates', models.ManyToManyField(blank=True, to='pages.Certificate', verbose_name='Сертификаты')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.instructor', verbose_name='Инструктор')),
            ],
            options={
                'verbose_name': 'Контент главной страницы',
                'verbose_name_plural': 'Контент главной страницы',
            },
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('introduction', models.TextField(verbose_name='Введение')),
                ('team_description', models.TextField(blank=True, null=True, verbose_name='Описание команды')),
                ('team_image', models.ImageField(blank=True, null=True, upload_to='about/team/', verbose_name='Изображение команды')),
                ('team_photo', models.ImageField(blank=True, null=True, upload_to='about/team/', validators=[pages.validators.validate_image_file_size, pages.validators.validate_file_extension], verbose_name='Фото команды')),
                ('mission_statement', models.TextField(verbose_name='Наша миссия')),
                ('mission_photo', models.ImageField(blank=True, null=True, upload_to='about/mission/', validators=[pages.validators.validate_image_file_size, pages.validators.validate_file_extension], verbose_name='Фото миссии')),
                ('mission_image', models.ImageField(blank=True, null=True, upload_to='about/mission_image/', validators=[pages.validators.validate_image_file_size, pages.validators.validate_file_extension], verbose_name='Изображение миссии')),
                ('services', models.TextField(verbose_name='Наши услуги')),
                ('services_image', models.ImageField(blank=True, null=True, upload_to='about/services_image/', validators=[pages.validators.validate_image_file_size, pages.validators.validate_file_extension], verbose_name='Изображение услуг')),
                ('contact_info', models.TextField(verbose_name='Связь с нами')),
                ('social_links', models.JSONField(blank=True, null=True, verbose_name='Ссылки на соцсети')),
                ('instructors', models.ManyToManyField(blank=True, to='pages.Instructor', verbose_name='Инструкторы')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
