# Generated by Django 3.2 on 2025-04-05 16:01

from django.db import migrations, models
import django.db.models.deletion
import pages.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название оборудования')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('image', models.ImageField(upload_to='equipment/', validators=[pages.validators.validate_image_file_size, pages.validators.validate_file_extension], verbose_name='Изображение')),
                ('detailed_description', models.TextField(blank=True, help_text='Подробная информация о ремонтных работах и услугах', null=True, verbose_name='Подробное описание ремонта')),
            ],
            options={
                'verbose_name': 'Ремонт оборудования',
                'verbose_name_plural': 'Ремонт оборудования',
            },
        ),
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория оборудования',
                'verbose_name_plural': 'Категории оборудования',
            },
        ),
        migrations.CreateModel(
            name='EquipmentPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ремонт оборудования', max_length=255, verbose_name='Заголовок страницы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Вступительный текст страницы')),
                ('background_photo', models.ImageField(blank=True, null=True, upload_to='equipment_page/', validators=[pages.validators.validate_image_file_size, pages.validators.validate_file_extension], verbose_name='Фоновое изображение')),
                ('equipment', models.ManyToManyField(blank=True, related_name='equipment_page', to='equipment.Equipment', verbose_name='Список ремонтируемого оборудования')),
            ],
            options={
                'verbose_name': 'Контент страницы ремонта оборудования',
                'verbose_name_plural': 'Контент страницы ремонта оборудования',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.equipmentcategory', verbose_name='Категория'),
        ),
    ]
