# Generated by Django 3.2 on 2025-04-05 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название курса')),
                ('course_category', models.CharField(choices=[('regular', 'Обычные курсы'), ('sdi_specialization', 'Специализации SDI'), ('first_response', 'Курсы первой медицинской помощи')], default='regular', max_length=20, verbose_name='Тип курса')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('included', models.TextField(verbose_name='Что входит в курс')),
            ],
            options={
                'verbose_name': 'Курс обучения',
                'verbose_name_plural': 'Курсы обучения',
            },
        ),
        migrations.CreateModel(
            name='TrainingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание страницы')),
                ('advantages', models.TextField(verbose_name='Преимущества обучения')),
            ],
            options={
                'verbose_name': 'Страница обучения',
                'verbose_name_plural': 'Страницы обучения',
            },
        ),
        migrations.CreateModel(
            name='TrainingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='training_videos/', verbose_name='Видео курса')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='training.trainingcourse', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Видео курса',
                'verbose_name_plural': 'Видео курсов',
            },
        ),
        migrations.CreateModel(
            name='TrainingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='training_images/', verbose_name='Изображение курса')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='training.trainingcourse', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Изображение курса',
                'verbose_name_plural': 'Изображения курсов',
            },
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='training_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='training.trainingpage', verbose_name='Страница обучения'),
        ),
    ]
