# Generated by Django 3.2 on 2026-03-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='cta_description',
            field=models.TextField(blank=True, default='Свяжитесь с нами для записи на курс', verbose_name='Описание CTA'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='cta_title',
            field=models.CharField(blank=True, default='Записаться на курс', max_length=100, verbose_name='Заголовок CTA'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='section_gallery_title',
            field=models.CharField(blank=True, default='Галерея', max_length=100, verbose_name='Заголовок галереи'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='section_video_title',
            field=models.CharField(blank=True, default='Видео', max_length=100, verbose_name='Заголовок видео'),
        ),
    ]
