# Generated by Django 3.2 on 2025-04-05 16:01

from django.db import migrations, models
import django.utils.timezone
import pages.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', validators=[pages.validators.validate_image_file_size, pages.validators.validate_file_extension])),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
